#!/usr/bin/env bash

# Contains a list of packages to install.
# To remove a package simply comment it out using the hashtag symbol #
# To add a package simply remove the hashtag symbol #
# TO add a package not present in the lists, simply add '{package_name}' to a new
# line, where {package_name} is the name of the package.

# STANDARD PACKAGES
packages=(
    #*********** SYSTEM/DRIVER SETUP ***************************************#
    'xorg'                          # A Group package that contains extra xorg-apps
    'xorg-xinit'                    # Useful For Starting Window Managers from a TTY 
    
    #'linux-lts-headers'             # Headers For LTS Kernel            
    #'linux-headers'                # Headers For Kernel                
    #'linux-zen-headers'            # Headers For ZEN Kernel            
    #'linux-hardened-headers'       # Headers For Hardened Kernel   

    #'nvidia'                       # Nvidia Graphics Driver
    #'nvidia-lts'                   # Nvidia LTS Graphics Driver
    #'lib32-nvidia-utils'           # Nvidia OpenGL Library - Needed For Games and Steam
    #'xf86-video-amdgpu'            # AMD Driver
    #'xf86-video-ati'               # ATI Driver
    #'lib32-mesa'                   # AMD/ATI OpenGL Library - Needed For Games and Steam

    #*********** SYSTEM TOOLS SETUP ****************************************#
    'mtools'                        # MS-DOS Disk Tools
    'cronie'                        # Run Services At Specific Times
    'dosfstools'                    # DOS Filesystem Utilities
    'os-prober'                     # Detects other OSs
    'ntfs-3g'                       # Mount and interact with NTFS (Windows) drives.
    'wget'                          # File Downloader
    'curl'                          # File Downloader
    'hwinfo'                        # Hardware CLI tool
    'htop'                          # CLI Task Manager
    'dmidecode'                     # Interface For Memory
    'iputils'                       # Network Tools
    'traceroute'                    # Packet Route Tracking
    'iproute2'                      # Contains Network Tools
    'fail2ban'                      # IP Banner
    'parted'                        # Terminal Partitioning Tool
    'hdparm'                        # Used For Getting Disk Speeds
    'lm_sensors'                    # Used For Getting Temperature Readings
    'ffmpeg'                        # CLI Audio Tool
    'mlocate'                       # File/Folder location CLI Tool
    'udisks2'                       # Storage Device Daemon
    'udiskie'                       # Auto Mounter With Support For LUKS
    'bzip2'                         # Unpack .bz2,bz,tbz2,tbz Files
    'gzip'                          # Unpack .gz,.z,.tgz,.taz Files
    'unzip'                         # Unpack .zip files
    'p7zip'                         # Unpack .7z Files
    'unrar'                         # Unpack .rar Files
    
    #*********** PROGRAMMING LANGUAGE / DEVELOPMENT TOOLS SETUP ************#
    'make'                          # Linux Build Tool
    'cmake'                         # Cross Platform Build Tool
    'git'                           # Project Management
    'nasm'                          # Assembler
    'gcc'                           # C/C++ Compiler
    'gdb'                           # C/C++ Debugger
    'clang'                         # Clang C/C++ Compiler
    'cppcheck'                      # Compile-time C++ Checker
    'nodejs'                        # Node.js
    'npm'                           # Node Package Manager
    'rust'                          # Rust Package
    'ghc'                           # Haskell Compiler
    'jdk-openjdk'                   # Java SDK
    'dotnet-sdk'                    # .NET SDK
    'mono'                          # Mono For C#
    'apache'                        # Apache HTTP Web Server
    'ruby'                          # Ruby Scripting Language
    'ruby-irb'                      # Interactive Ruby Shell
    'python-pip'                    # Python3 PIP
    'glfw'                          # OpenGL Library
    'glew'                          # OpenGL Library

    #*********** UTILITY APPLICATIONS SETUP ********************************#
    'openvpn'                       # For VPN Connections
    'ufw'                           # Firewall
    'apparmor'                      # Security Software
    'firejail'                      # Sandboxing Security Software
    'grub-customizer'               # Grub Configurator
    'gparted'                       # Disk Management 

    #*********** FONTS & APPEARANCE SETUP ***********************************************#
    'ttf-liberation'                # Free Compatible Versions Like Arial Fonts
    #'papirus-icon-theme'            # Papirus Icon Theme Set 
    #'ttf-ubuntu-font-family'       # Adds Ubuntu Fonts
    #'ttf-roboto'                   # Adds Roboto Fonts

    #*********** APPLICATIONS SETUP ************#
    'zsh'                           # Alternative Shell to Bash
    'zsh-completions'               # Auto Completions For ZSH
    #'bash-completions'             # Auto completions for BASH
    'firefox'                       # Firefox Browser
    #'chromium'                     # Chromium Web Browser
    'discord'                       # Communication
    #'code'                          # VSCode Editor 
    #'plank'                         # A Docker
    #'flameshot'                     # Screenshot software
    #'neovim'                        # Neo Vim - More plugin Support
    #'obs-studio'                    # Recording and Streaming
    #'gimp'                          # Image Editor
    #'feedreader'                    # RSS Reader
    #'youtube-dl'                    # Youtube Downloader CL Program
    #'libreoffice-still'             # Office Writer
    #'virtualbox'                    # Virtual Machine 
    #'virtualbox-host-dkms'          # Virtual Machine Dependency for Other kernels.    }    
    #'virtualbox-host-modules-arch' # Virtual Machine Dependency for standard kernel.  } ONLY 1 OF THESE PACKAGES
)

# AUR PACKAGES
packagesaur=(
    'protonvpn-cli-ng'                     # ProtonVPN CLI Client
    'zeal-git'                             # Offline Documentation Viewer
    'timeshift'                            # Backup Tool
    'bitwarden-bin'                        # Password Manager
    #'breeze-obsidian-cursor-theme'        # Obsidian Cursor Theme
    #'gnome-shell-pomodoro'                # Pomodoro Timer for Gnome
    #'gnome-shell-extension-pop-shell-git' # Tiling Windows for Gnome
 )

# PYTHON-PIP PACKAGES
packagespip=(   
    #'PyQt5'                         # Python wrapper of QT UI Library
    #'selenium'                      # Python Library For Web Engine Automation
    #'numpy'                         # Pythson Math Library
    #'matplotlib'                    # Python Graph Plotting Library
    #'gym'                           # Comparing reinforcement learning algorithms.
    #'opencv-python'                 # Library for Real Time Applications
    #'pandas'                        # Data Anaylsis Tool
)

# VISUAL STUDIO CODE EXTENSIONS
extensionscode=(
    #'ms-python.python'                          # Python Language 
    #'ms-vscode.cpptools'                        # C/C++ Language
    #'ms-dotnettools.csharp'                     # C# Language
    #'twxs.cmake'                                # CMake Support
    #'alefragnani.project-manager'               # Project Manager
    #'miqh.core-theme'                           # Core Themes
 )