name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Get Arch-Linux Image
      run: docker pull archlinux
    - name: Run Arch-Linux Image
      run: docker run -it -d archlinux bin/bash; docker container ls; docker exec -it archlinux echo "Hello from container!"
